accounts/urls.py
from django.urls import path
from .views import UserSignUpView

urlpatterns = [
	path('signup/',UserSignUpView.as_view(),name='signup'),
	]

fast_food/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
# keyingi holatlar uchun
from . import views
urlpatterns = [
	path('',HomePageView.as_view(),name='index'),
	
	# path('menu/',MenuPageView,name='menu'), # avvalgi holat
	path('menu/',views.menuPageView,name='menu'), # keyingi holat
	# updateItem uchun
	path('update_item/',views.updateItem),
	# cart funsiyasi uchun 
	path('cart/', views.cart, name="cart"),

	path('book/',BookPageView,name='book'),
	path('about/',AboutPageView.as_view(),name='about'),
	path('product_create/',ProductCreateView.as_view(),name='product_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 4- bosqichda menu html fayliga Add Cart bo'limini yozishimiz kerak

src/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('',include('fast_food.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

fast_food/models.py
from django.db import models
from django.contrib.auth.models import User

# Mahsulotlarimizni saqlash uchun model
class Mahsulotlar(models.Model):
	mahsulot_nomi = models.CharField(max_length=200)
	mahsulot_tarkibi = models.TextField()
	mahsulot_rasmi = models.ImageField(upload_to='images/')
	mahsulot_narxi = models.FloatField()

	# String obyektini qaytaradi
	def __str__(self):
		return self.mahsulot_nomi


# 1-bosqich

# Order ya'niy mahsulotni savatga qushish uchun model
# from django.contrib.auth.models import User
class Order(models.Model):
	customer = models.ForeignKey(User, on_delete=models.SET_NULL,blank=True,null=True)
	date_orderd = models.DateTimeField(auto_now_add=True)
	name  = models.CharField(max_length=200, null=True)
	complete = models.BooleanField(default=False,null=True,blank=False)

	'''pastdagi get_total funsiyasidan qaytgan qiymatni
	     barcha orderItem(savatdagi mahsulotlar) larni hisoblash uchun'''

	     
	@property # Dekorator
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total


	'''pastdagi quantity(mahsulotlarni sonini) va 
	     barcha orderItem(savatdagi mahsulotlar) larni hisoblash uchun'''
	@property # Dekorator
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total  = sum([item.quantity for item in orderitems])
		return total


	# String obyektini qaytaradi
	def __str__(self):
		return str(self.id)

# Mahsulotni qachon va kim tomonidan qaysi mahsulot qushilganligni saqlash uchun model
class OrderItem(models.Model):
	product = models.ForeignKey(Mahsulotlar, on_delete=models.SET_NULL,blank=True,null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL,blank=True,null=True)
	quantity = models.IntegerField(default=0,null=True,blank=True)
	date_added = models.DateTimeField(auto_now_add=True)


	# mahsulot narxni soniga ko'paytirib beradi
	@property # Dekorator
	def get_total(self):
		total = self.product.mahsulot_narxi * self.quantity
		return total

	# String obyektini qaytaradi
	def __str__(self):
		return str(self.id)


class Comments(models.Model):
	userName = models.CharField(max_length=150,null=True)
	phone = models.CharField(max_length=20)
	email = models.CharField(max_length=50)
	message = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	


	def __str__(self):
		return f'{self.userName}'
		


# 2-bosqich

# ==> base.htmlga savatni rasmini hosil qilamiz

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy

class UserSignUpView(generic.CreateView):
	form_class = UserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'signup.html'

fast_food/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView, CreateView
from .models import Mahsulotlar, Comments
from django.core.paginator import Paginator
import requests
from django.urls import reverse_lazy


# keyingi holatlar uchun
from .models import *
from django.http import JsonResponse
import json

class HomePageView(ListView):
	model = Mahsulotlar
	template_name = 'index.html'


# 3-bosqich
# avvalgi holat
# def MenuPageView(request):
# 	obj = Mahsulotlar.objects.all()
# 	page_n = request.GET.get('page',1)
# 	p = Paginator(obj,3)
# 	try:
# 		page = p.page(page_n)
# 	except Exception:
# 		page = p.page(1)
# 	context = {
# 	'page': page
# 	}
# 	return render(request,'menu.html',context)


# keyingi holat
def menuPageView(request):
	if request.user.is_authenticated:
		customer = request.user
		print(request.user)
		order, created = Order.objects.get_or_create(customer=customer,complete=False)
		items = order.orderitem_set.all()
		cartItems = order.get_cart_items # savatdagi mahsulotlar soni
	else:
		items = []
		order = {'get_cart_total': 0, "get_cart_items": 0}
		cartItems = order['get_cart_items'] # qaysi funksiya orqali hisoblasin

	obj = Mahsulotlar.objects.all()
	page_n = request.GET.get('page',1)
	p = Paginator(obj,3)
	try:
		page = p.page(page_n)
	except Exception:
		page = p.page(1)
	context = {
	'page': page,
	'cartItems':cartItems
	}
	return render(request,'menu.html',context)
# ====> urls.py fayilimizda davom etamiz


# from django.http import JsonResponse
# import json
# Mahsulotlarni qushishni bajarish uchun funsiya yozamiz
def updateItem(request):
	data = json.loads(request.body)
	productId = data['productId']
	action = data['action']
	# print('Bosildi: ',action) #terminalda mahsulot ID si ko'rinishi kerak
	# print('Mahsulot IDsi: ',productId)

	# keyingi uzgarish POST create qilish
	# base.html dagi savat iconi ga  mahsulot soni korsatishimiz kerak
	customer = request.user
	product = Mahsulotlar.objects.get(id=productId)
	order, created = Order.objects.get_or_create(customer=customer,complete=False)

	orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

	if action == 'add':
		orderItem.quantity = (orderItem.quantity + 1)
	elif action == 'remove':
		orderItem.quantity = (orderItem.quantity - 1)
	
	orderItem.save()

	if orderItem.quantity <= 0:
		orderItem.delete()

	return JsonResponse('Item was added', safe=False)
	# ushbu funksiyaga url yasashimiz kerak


# cart.html uchun funksiya
def cart(request):
	if request.user.is_authenticated:
		customer = request.user
		order, created = Order.objects.get_or_create(customer=customer,complete=False)
		items = order.orderitem_set.all()
		cartItems = order.get_cart_items
	else:
		# reverse_lazy('login')
		items = []
		order = {'get_cart_total': 0, "get_cart_items": 0}
		cartItems = order['get_cart_items']

	context = {"items": items,"order": order,'cartItems':cartItems }
	return render(request, 'cart.html', context)
	# ushbu funksiyaga url yasashimiz kerak
	# base html dagi savat urliga cart ni belgilab quyishimiz kerak





def telegram_bot_sendtext(bot_message):
  bot_token ='5130152396:AAGiHy6qCBX9Yc8cxEyhsbn1Twzk_pdWL5E'
  bot_chatID ='1129151347'
  send_text ='https://api.telegram.org/bot' + bot_token + '/sendMessage?chat_id=' + bot_chatID + '&parse_mode =Markdown&text=' + bot_message 
  response =requests.get(send_text)
  return response.json()





def BookPageView(request):
    if request.method == 'POST':
        name = request.POST.get('name',None)
        phone = request.POST.get('phone',None)
        email = request.POST.get('email',None)
        message = request.POST.get('message',None)
        user = Comments.objects.create(
            userName = name,
            phone = phone,
            email = email,
            message = message
            )
        user.save()
        telegram_bot_sendtext(f"Ismi: {name} \nTelfon raqam: {phone} \nEmail: {email} \nXabar jonatdi: {message}") 

       
    return render(
    request=request,
    template_name= 'book.html'
    )
# class BookPageView(TemplateView):
# 	template_name = 'book.html'


class AboutPageView(TemplateView):
	template_name = 'about.html'


class ProductCreateView(CreateView):
    model = Mahsulotlar
    template_name = 'product_create.html'
    # fields = ('mahsulot_nomi','mahsulot_tarkibi','mahsulot_rasmi','mahsulot_narxi')
    fields = '__all__'
    success_url = reverse_lazy('index')

templates/about.html
{% extends 'base.html' %}

{% block content %}

  <!-- about section -->

  <section class="about_section layout_padding">
    <div class="container  ">

      <div class="row">
        <div class="col-md-6 ">
          <div class="img-box">
            <img src="images/about-img.png" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                We Are ExpressEat
              </h2>
            </div>
            <p>
              There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
              in some form, by injected humour, or randomised words which don't look even slightly believable. If you
              are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in
              the middle of text. All
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->

  {% endblock content %}

templates/book.html
{% extends 'base.html' %}

{% block content %}
  <section class="book_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Book A Table
        </h2>
      </div>
      
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <form method ="post"> {% csrf_token %}
              <div>
                <input type="text" class="form-control" name ='name' placeholder="Ismingizni Kiriting" />
              </div>
              <div>
                <input type="text" class="form-control" name = 'phone' placeholder="Telfon raqamingizni Kiriting" />
              </div>
              <div>
                <input type="email" class="form-control" name = 'email' placeholder="Emailingizni Kiriting" />
              </div>
              <div>
                <input type="text" class="form-control" name = 'message' placeholder="Tavsiyalaringiz..." />
              </div>
             
              <div class="btn_box">
                <button>
                  Yuborish
                </button>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-6">
          <div class="map_container ">
            <div id="googleMap"></div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end book section -->

  {% endblock content %}

templates/cart.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <script src="{% static 'js/cart.js' %}"></script>
    <title>Shopping Cart UI</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart1.css' %}">
    <link rel="stylesheet" type="text/css" href="./style.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,900" rel="stylesheet">

    <script type="text/javascript"> 
  var user = '{{ request.user }}'

  function getToken(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
      var cookie = cookies[i].trim();
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}
var csrftoken = getToken('csrftoken');
  </script>


</head>
<body>
   <div class="CartContainer">
       <div class="Header">
        <h3 class="Heading">Shopping Cart </h3>
        <h5 class="Action">Remove all</h5>
       </div>
       {% for item in items %}
       <div class="Cart-Items">
          <div class="image-box">
            <img src="{{ item.product.mahsulot_rasmi.url }}" width="225px" height="200px" />
          </div>
          <div class="about">
            <h1 class="">{{ item.product.mahsulot_nomi }}</h1>
            <h3 class="subtitle"></h3>
            <img src=""/>
          </div>
          <div class="counter">
            <div class="btn" ><img data-product="{{ item.product.id }}" width="20px" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}"></div>
            <div class="count">{{ item.quantity }}</div>
            <div class="btn"><img data-product="{{ item.product.id }}" width="20px" data-action="remove"  class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}"></div>
          </div>
          <div class="prices">
            <div class="amount">${{ item.product.mahsulot_narxi }}</div>
            <div class="save"><u>Save for later</u></div>
            <div class="remove" data-product="{{ item.product.id }}" data-action="delete"><u>Remove</u></div>
          </div>
       </div>
       <br>
       {% endfor %}
     <hr> 
     <div class="checkout">
     <div class="total">
        <div>
            <div class="Subtotal">Sub-Total</div>
            <div class="items">{{ order.get_cart_items }}</div>
        </div>
        <div class="total-amount">${{ order.get_cart_total }}</div>
     </div>
     <button class="button">Checkout</button></div>
   </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

templates/product_create.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <!-- Basic -->






  






  
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Feane </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
 <style>
    #soz {
      white-space: nowrap;
      text-overflow: ellipsis;
      overflow: hidden;
    }
  </style>
</head>

<body >
  <!-- class="sub_page" -->

  <div class="hero_area">
    <div class="bg-box">
      <img src="{% static 'images/hero-bg.jpg' %}" alt="">
    </div>
    <!-- header section strats -->
    <header class="header_section">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'index' %}">
            <span>
              Feane
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  mx-auto ">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'menu' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'book' %}">Book Table</a>
              </li>
            </ul>

            <!-- login qismi -->
            <div class="user_option"><style>
/* Style The Dropdown Button */
.dropbtn {
        display: inline-block;
    padding: 10px 45px;
    background-color: #ffbe33;
    color: #ffffff;
    border-radius: 45px;
    -webkit-transition: all 0.3s;
    transition: all 0.3s;
    border: none;
    margin-top: 10px;
}
}

/* The container <div> - needed to position the dropdown content */
.dropdown {
  position: relative;
  display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
  display: none;
  position: absolute;

  min-width: 150px;
 /* box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);*/
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  border-radius: 45px;

}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #yellow;
color: #ffbe33;}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {
  display: block;
}

/* Change the background color of the dropdown button when the dropdown content is shown */
.dropdown:hover .dropbtn {
  background-color: #3e8e41;
}
</style>
 {% if user.is_authenticated %}
<div class="dropdown">
  <button class="dropbtn">{{ user.username|title }}</button>
  <div class="dropdown-content">
    <a href="#">Link 1</a>
    <a href="#">Link 2</a>
    <a href="{% url 'logout' %}">Chiqish</a>
  </div>
</div>
  

{% else %}
<form class="form-inline ml-auto">
<a href="{% url 'login' %}" class="order_online" style="margin: 15px;">
Saytga kirish</a>
<a href="{% url 'signup' %}" class="order_online">
Ro'yxatdan o'tish</a>
</form>
{% endif %}
             <!-- login qismi tugashi -->

            
            </div>
          </div>
        </nav>
      </div>
    </header>
    <hr>



<!-- book section -->
  <section class="book_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2 style="color:white;">
          Mahsulot yarating        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <form method="post"  enctype="multipart/form-data"> {% csrf_token %}
              <div>
                <input class="form-control" type="text" name="mahsulot_nomi" placeholder="Mahsulot nomi" maxlength="200" required="" id="id_mahsulot_nomi">
              </div>
              <div>
                <textarea class="form-control" placeholder="Mahsulot tarkibi" name="mahsulot_tarkibi" cols="40" rows="10" required="" id="id_mahsulot_tarkibi"></textarea>
              </div>

              <div>
                <h2 style="color:white">Rasm kiriting</h2>
                <input type="file" name="mahsulot_rasmi" accept="image/*" required="" id="id_mahsulot_rasmi">
              </div>
              <br>

              <div>
              <input class="form-control" placeholder="Mahsulot narxi" type="text" name="mahsulot_narxi" maxlength="10" required="" id="id_mahsulot_narxi">
              </div>
            
             
              <div class="btn_box">
                <button type="submit">
                  Yuborish
                </button>
              </div>
            </form>
          </div>
        </div>
      
      </div>
    </div>
  </section>


<!-- djangoni kodi -->



<!-- djangoni kodi -->




<!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              Contact Us
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              Feane
            </a>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-pinterest" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Opening Hours
          </h4>
          <p>
            Everyday
          </p>
          <p>
            10.00 Am -10.00 Pm
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a><br><br>
          &copy; <span id="displayYear"></span> Distributed By
          <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
        </p>
      </div>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->

</body>
 
</html>


<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p}}
  <button type="submit">yuborish</button>

</form>